name: Deploy Storybook to Github pages
on:
  push:
    branches:
      - 'development'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Yarn
        run: npm i -g yarn
      - name: Install package.json dependencies
        run: yarn install
      - name: Build storybook
        run: yarn run storybook:build
      - name: No Jekyll option
        run: touch documentation/storybook/storybook-static/.nojekyll
      - name: Upload build artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: documentation/storybook/storybook-static
          if-no-files-found: error
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: docs
          path: storybook
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: storybook
